name: Actions Workflow

on: 
  # push:
  
  # A scheduled event
  schedule:
    # Minutes, Hours, DayOfMonth, Month, DayOfWeek (UTC Times)

    # Means run every minute, every hour, every DayOfMonth, every Month, every DayOfWeek
    #- cron: "* * * * * "

    # Means run on minute 1 of every hour, every DayOfMonth, every Month, every DayOfWeek
    #- cron: "1 * * * * " 

    # Means run on minutes 1 and 5 of every hour, every DayOfMonth, every Month, every DayOfWeek
    #- cron: "1,5 * * * * " 

    # Means run on minutes 1 to 5 of every hour, every DayOfMonth, every Month, every DayOfWeek
    #- cron: "1-5 * * * * " 

    # Means every 15 minutes(starting on minute 0), every hour, every DayOfMonth, every Month, every DayOfWeek
    #- cron: "0/15 * * * * " 

    # Run at 12 and 2 every day
    #- cron: "0 12,2 * * * " 

    # Run at 12 pm, every month on day 1"
    #- cron: "0 12 1 * * " 

    # Run at 12 pm, on day 1, in January"
    #- cron: "0 12 1 1 * " 

    # Run at 12 pm, on Sundays (0-6 where 0 is Sunday and 6 is Saturday)
    #- cron: "0 12 * * 0" 

    # At 12:00 on Sunday in February" 
    #- cron: "0 12 * FEB 0" 

    # At 12:00 on Monday in February" 
    #- cron: "0 12 * FEB MON" 

    # Every 2 minutes 
    - cron: "0/2 * * * *" 
    # ... and every 6 minutes
    - cron: "0/3 * * * *" 

  pull_request:
    # You can specify activity types as objects
    types: [closed, assigned, opened, reopened] 

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: List Files After Checkout
        run: | 
          pwd
          ls -a 
          # These env vars are set automatically
          # This is the commit SHA ID that triggered this action to run
          echo $GITHUB_SHA
          # This is the repository name
          echo $GITHUB_REPOSITORY
          # This is the workspace directory
          echo $GITHUB_WORKSPACE
          # This is a token you can use to authenticate with the github repo
          echo "${{ github.token }}" 
          # Just ideas: (you'll need to google how to embed your github.token here )
          #    git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          #    git checkout $GITHUB_SHA 
      - name: Simple JS Action
        id: greet
        # you can reference a branch (e.g. master), a tag version (i.e. v1), or a commit number
        # Using a branch is usually discouraged since it can change.
        uses: actions/hello-world-javascript-action@v1
        # Use the 'with' key to provide an input to the action
        with:
          who-to-greet: John
      - name: Log Greeting Time
        # Reference another action's output
        run: echo "${{ steps.greet.outputs.time }}" 
