name: Docker CUDA 10.2 and Ubuntu 16.04
on: push

jobs:
  docker-steps:
    # Docker containers can only run on ubuntu, it cannot run on Mac or Windows.
    runs-on: ubuntu-latest 
    container:
      # docker://10.2-devel-ubuntu16.04
      image: nvidia/cuda:10.2-devel-ubuntu16.04

    steps:
      - name: Log running docker containers
        run: docker -ps 
