name: Matrix
on: push

jobs:
  node-version:
    steps:
      - name: Log node version before changing versions
       run: node -v

      - uses: actions/setup-node@v1
       with:
         node-version: 6

      - name: Log node version after changing versions
        run: node -v 
