name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        # The following will run 9 jobs
        # Two permutations of operating systems
        os: [windows-latest, ubuntu-latest, macos-latest]
        # This will run the job 3 times, once for each of the versions below
        node_version: [6,8,10]

      # Indicates the maximum number of jobs allowed to run at once.
      max-parallel: 2 

      # This means if one of the above 3 fails, the others will also stop
      # If set to false, then the other jobs will continue to run
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Log node version before changing versions
        run: node -v

      - uses: actions/setup-node@v1
        with:
          #node-version: 6
          node-version: ${{ matrix.node_version }}

      - name: Log node version after changing versions
        run: node -v 
