name: Dockerized NodeJs App
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest

    # Instead of the 'container' key, specify 'services'
    services: 
      # The following is very similar to a docker_compose.yml file
      app: 
        # Specify the username/imagename on dockerhub.com
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps: 
      - name: Post a user
        # Send a HTTP POST request to create a user to the mongo DB.
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application: application/json'' -d ''{\"username\": \"hello\", \"address\": \"dwded\"}''' 
      - name: Get Users
        run: curl http://localhost:3001/api/users
        
        

      
      
