name: Shell Commands

# A single event or An array of events.  The VScode plugin will autogenerate the events available.
on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    # The maximum number of minutes the job can take
    timeout-minutes: 360
    steps: 
      - name: echo a string
        run: echo "hello"
        # This indicates if there's an error, continue running subsequent steps regardless.
        continue-on-error: true
        # The maximum number of minutes before github will cancel a step
        timeout-minutes: 5
      - name: echo another string
        run: echo "goodbye" 
      - name: multiline script
        # The pipeline symbol allows us to run multiple commands
        run: | 
          node -v
          npm -v 
        # This would indicate if there was a failure, this step should run
        # if: failure()
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-commands:
    runs-on: windows-latest
    # You can specify one or more dependency jobs using 'needs'
    needs: ["run-shell-command"]
    steps: 
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        # Specify a different shell than the default (powershell) shell
        shell: bash
